{
 "title": "Novy TDS Solana",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(solana_active_validators, service)"
   }
  ]
 },
 "panels": [
  { "title": "Validator's Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Stake",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "SOL" }
   ],
   "targets": [
    {
     "expr": "solana_validator_activated_stake{pubkey=\"HY5WoZZBthNFH3EaKbo8piwwR3joyjprqvzdrX1h9GTw\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Delinquent Validator",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_delinquent{pubkey=\"HY5WoZZBthNFH3EaKbo8piwwR3joyjprqvzdrX1h9GTw\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Last Vote",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_last_vote{pubkey=\"HY5WoZZBthNFH3EaKbo8piwwR3joyjprqvzdrX1h9GTw\"}"
    }
   ]
  },
  {
   "title": "Root Slot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_root_slot{pubkey=\"HY5WoZZBthNFH3EaKbo8piwwR3joyjprqvzdrX1h9GTw\"}"
    }
   ]
  },
  { "title": "Network Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "validator desync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_validator_last_vote - on(service) group_left() max by(env, service) (solana_validator_last_vote{service=~\"$service\"}) > -500000"
    }
   ]
  },
  {
   "title": "rate(max(last_voted))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(max by(env, service) (solana_validator_last_vote{service=~\"$service\"})[1m:])"
    }
   ]
  },
  {
   "title": "active / delinquent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solana_active_validators{service=~\"$service\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "max(root_slot)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_root_slot{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "max(last_voted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(solana_validator_last_vote{service=~\"$service\"})"
    }
   ]
  }
 ]
}